#Cargo.toml
[package]
name = "rust-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1.38.0", features = ["full"] }
tower = "0.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"