# config.yaml - Database configuration file

database:
  host: "dpg-d138hojuibrs73fu816g-a.oregon-postgres.render.com"
  port: 5432
  dbname: "items_vs0o"
  username: "customer"
  password: "123"
  max_connections: 20  # Increase from 10

server:
  host: "0.0.0.0"
  port: 3000