# render.yaml - Render.com deployment configuration

services:
  - type: web
    name: rust-api
    env: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/rust-api
    envVars:
      - key: RUST_LOG
        value: info
      - key: DB_HOST
        value: dpg-d138hojuibrs73fu816g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: items_vs0o
      - key: DB_USER
        value: customer
      - key: DB_PASSWORD
        value: "123"
      - key: DB_MAX_CONNECTIONS
        value: 10
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
