#render.yaml
services:
  - type: web
    name: rust-api
    env: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/rust-api
    envVars:
      - key: RUST_LOG
        value: info

postgresql:
  host: dpg-d138hojuibrs73fu816g-a.oregon-postgres.render.com
  port: 5432
  dbname: items_vs0o
  username: admin
  password: pFR6dANbqkqzhD8cvgsS9YmcVPy35JQW